# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 92df3ab3361980a03a49bc25ba03028ff1cff3e3bb6fe21aecf5d04ad0044e4da1d5ead0d8629888fe0933dbb1bab9df35c2421a25112d381e08667be77f2122

test:
  secret_key_base: 78bdf0b7fe3ebcd98a3f870b227685080dfe7c61790769148190ec360a044966d9e5b6a3bfa53278e123a7a3725ecd282aeb018c4c599a6d0a4b4818674ff880

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
